export { default as apiClient } from './client'
export { authService } from './authService'
export { usuariosService } from './usuariosService'
export { alumnosService } from './alumnosService'
export { tiposDocumentoService } from './tiposDocumentoService'
export { configuracionService } from './configuracionService'
export { perfilDiscapacidadService } from './perfilDiscapacidadService'
export { bitacoraService } from './bitacoraService'
export { indicadoresService } from './indicadoresService'
export { documentosExpedienteService } from './documentosExpedienteService'
export { entradaArchivosService } from './entradaArchivosService'
